version: 0.2
env:
  git-credential-helper: yes
  shell: bash
phases:
  install:
    runtime-versions:
      docker: 19
      nodejs: 12
  pre_build:
    commands:
      # Install yq
      - wget https://github.com/mikefarah/yq/releases/download/v4.12.0/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
      - yq --version
      # Import credentials
      - jq -c '.token = "${GITHUB_TOKEN}"' import-source-credentials.json > tmp.$$.json && mv tmp.$$.json import-source-credentials.json
      - aws codebuild import-source-credentials --cli-input-json file://import-source-credentials.json
      - aws codebuild list-source-credentials
      # Install nodejs application dependencies
      - echo "Installing dependencies..."
      - npm install 
  build:
    commands:
      - echo Build started on `date`
      # Run test
      - echo Run node.js tests...
      - npm run test
      # Get application version 
      - CONTAINER_IMAGE_TAG="$(node -e "console.log(require('./package.json').version);")"
      # Build the Docker images
      - echo Building the Docker image...
      - docker build -t lukondefmwila/ecommerce-orders:$CONTAINER_IMAGE_TAG .
      # Log in to the Docker CLI
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
      - cd ..
  post_build:
    commands:
      # Push the image to Docker hub
      - echo Pushing the Docker image...
      - docker push lukondefmwila/ecommerce-orders:$CONTAINER_IMAGE_TAG
      # Push local changes to remote repo
      - echo "Create temporary folder to clone the repo into..."
      - TEMP_FOLDER="$(mktemp -d)"
      - echo "Clone the repository..."
      - git clone -b main "https://LukeMwila:${GITHUB_TOKEN}@github.com/LukeMwila/microservice-example-helm-charts.git" ${TEMP_FOLDER}
      - cd ${TEMP_FOLDER}/application-charts/orders
      # Update Helm chart values-dev with new image tag
      - yq e -i '.orders.deployment.imageTag = env(CONTAINER_IMAGE_TAG)' ./values-dev.yaml
      - echo 'Container image tag updated in orders/values-dev.yaml'
      # Redirect back to root of temporary folder
      - cd ../../
      - git config user.email "lukemwila.tech@gmail.com"
      - git config user.name "LukeMwila"
      - git add . 
      - git commit -m "refactor - updated Helm chart values for dev environment with container image - $CONTAINER_IMAGE_TAG"
      - git push -u origin main